### ISSUE TITLE
[circleci] build failed

### ISSUE THREAD

**Issue by akinaru-lu** [akinaru-lu/lmm#563]
>[Note] Aborted connection 8 to db: 'lmm_test' user: 'root' host: 'api.api_default' (Got an error reading communication packets)

???

**Comment by akinaru-lu** [comment]
> api      | panic: context: internal error: missing cancel error
api      | 
api      | goroutine 103 [running]:
api      | context.(*cancelCtx).cancel(0xc000059e80, 0x0, 0x0, 0x0)
api      | 	/usr/local/go/src/context/context.go:350 +0x258
api      | context.propagateCancel.func1(0x8103c0, 0xc00034b340, 0x80e120, 0xc000059e80)
api      | 	/usr/local/go/src/context/context.go:262 +0x145
api      | created by context.propagateCancel
api      | 	/usr/local/go/src/context/context.go:259 +0x18d

**Comment by akinaru-lu** [comment]
reason: reason did not be called after os.Exit(int)
